"""add stations_cache table

Revision ID: dc0bbae62e9e
Revises: e110c71a34f5
Create Date: 2026-05-29 18:22:11.962191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0bbae62e9e'
down_revision: Union[str, Sequence[str], None] = 'e110c71a34f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations_cache',
    sa.Column('station_number', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('huc_code', sa.String(), nullable=True),
    sa.Column('basin', sa.String(), nullable=True),
    sa.Column('years_of_record', sa.Integer(), nullable=True),
    sa.Column('record_start_date', sa.String(), nullable=True),
    sa.Column('last_observation_date', sa.String(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('station_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stations_cache')
    # ### end Alembic commands ###
